pipeline{
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd maven_project && mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd maven_project && mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Simulando un despliegue a un servidor de aplicaciones...'
            }
        }
    }
    post {
        always {
            echo 'Este bloque se ejecuta siempre.'
        }
        success {
            echo 'Se ejecuta si el pipeline tuvo éxito.'
        }
        failure {
            echo 'Se ejecuta si el pipeline falló.'
        }
    }
}